import { Link } from 'react-router-dom';
import { NewsCard } from '../components/NewsCard';
import { mockNews } from '../lib/mockData';

const previewItems = mockNews;
const FEATURES = [
  { icon: '01', title: 'Real-time signals', desc: 'News aggregated from trusted financial sources and processed into clear market signals.' },
  { icon: '02', title: 'AI sentiment analysis', desc: 'Every headline is classified Bullish, Bearish, or Neutral with a visible confidence score.' },
  { icon: '03', title: 'Actionable insights', desc: 'Skip the fluff. Get a concise trading insight for each story in plain English.' },
];

export function LandingPage() {
  return <main className="min-h-screen overflow-x-hidden bg-[#18181b]">
    <nav className="border-b-2 border-white/10"><div className="mx-auto flex h-14 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><span className="border-2 border-bullish px-1.5 py-0.5 text-xl font-black uppercase tracking-tighter text-bullish shadow-[6px_6px_0_#ef4444]">Brief</span><Link to="/login" className="border-2 border-white px-4 py-2 text-[10px] font-black uppercase tracking-widest text-white shadow-[4px_4px_0_#fff] transition hover:bg-white hover:text-black">Sign in</Link></div></nav>
    <section className="relative overflow-hidden border-b-2 border-white/10 py-20 sm:py-24"><div className="pointer-events-none absolute inset-0 hero-grid" /><div className="pointer-events-none absolute inset-0" style={{ background: 'radial-gradient(ellipse 80% 70% at 50% 0%, transparent 40%, #18181b 100%)' }} /><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><div className="mb-6 inline-flex items-center gap-2 border-2 border-bullish px-3 py-1 shadow-[4px_4px_0_#ef4444]"><span className="h-2 w-2 bg-bullish" /><span className="text-[10px] font-black uppercase tracking-widest text-bullish">Live / AI-powered / free</span></div><h1 className="mb-6 text-5xl font-black uppercase leading-none tracking-tight text-white sm:text-7xl">Cut the <span className="bg-white px-2 text-black">noise.</span><br />Trade the <span className="text-bullish">signal.</span></h1><p className="mb-10 max-w-xl text-lg font-medium leading-relaxed text-white/60">Brief aggregates financial news from trusted sources and uses AI to surface what actually matters — sentiment, summaries, and actionable context.</p><div className="flex flex-wrap gap-4"><Link to="/login" className="border-2 border-bullish bg-bullish px-8 py-4 text-sm font-black uppercase tracking-widest text-white shadow-[4px_4px_0_#fff] transition hover:-translate-y-0.5">Get started — it’s free</Link><a href="#preview" className="border-2 border-white px-8 py-4 text-sm font-black uppercase tracking-widest text-white shadow-[4px_4px_0_#fff] transition hover:-translate-y-0.5">See it live ↓</a></div></div></div></section>
    <section className="mx-auto max-w-7xl border-b-2 border-white/10 px-4 py-12 sm:px-6 lg:px-8"><div className="grid grid-cols-1 gap-5 sm:grid-cols-3">{FEATURES.map((feature) => <article key={feature.title} className="bg-surface border-2 border-white p-6 shadow-[4px_4px_0_#fff]"><div className="mb-5 text-3xl font-black text-bullish">{feature.icon}</div><h2 className="mb-2 text-lg font-black uppercase tracking-tight text-white">{feature.title}</h2><p className="text-sm font-medium leading-relaxed text-white/50">{feature.desc}</p></article>)}</div></section>
    <section id="preview" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="mb-8"><h2 className="mb-2 text-3xl font-black uppercase tracking-tight text-white">Live feed preview</h2><p className="text-sm font-medium text-white/40">This is what your dashboard looks like — updated with AI analysis.</p></div><div className="relative"><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-3">{previewItems.map((item) => <NewsCard key={item.id} item={item} />)}</div><div className="pointer-events-none absolute inset-x-0 bottom-0 h-32 bg-gradient-to-t from-[#18181b] to-transparent" /><div className="relative flex justify-center pt-8"><Link to="/login" className="pointer-events-auto border-2 border-bullish bg-bullish px-6 py-3 text-sm font-black uppercase tracking-widest text-black shadow-[4px_4px_0_#ef4444] transition hover:-translate-y-0.5">Unlock full feed →</Link></div></div></section>
    <footer className="border-t-2 border-white/10 py-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-4 sm:flex-row sm:px-6 lg:px-8"><span className="border-2 border-bullish px-1.5 py-0.5 text-lg font-black uppercase tracking-tighter text-bullish">Brief</span><p className="text-center text-[10px] font-bold uppercase tracking-widest text-white/20">© 2026 Brief / Not financial advice / AI-generated content</p></div></footer>
  </main>;
}
